#!/bin/bash
# =============================================================
# AWS EC2 t3.micro Bootstrap Script
# URL Shortener — Zero-cost deployment on AWS Free Tier
#
# Usage:
#   Paste into EC2 → Advanced Details → User Data when launching
#   OR ssh in and run: bash scripts/ec2-setup.sh
#
# What this installs:
#   - Docker + Docker Compose
#   - Clones repo + starts all services
#   - Configures system limits for high concurrency
# =============================================================

set -euo pipefail

LOG="/var/log/url-shortener-setup.log"
exec > >(tee -a "$LOG") 2>&1

echo "========================================"
echo " URL Shortener EC2 Setup"
echo " $(date)"
echo "========================================"

# ── 1. System updates ─────────────────────────────────────────────
echo "[1/7] Updating system..."
apt-get update -q
apt-get upgrade -y -q

# ── 2. Install Docker ─────────────────────────────────────────────
echo "[2/7] Installing Docker..."
curl -fsSL https://get.docker.com | sh
usermod -aG docker ubuntu
systemctl enable docker
systemctl start docker

# Docker Compose plugin
apt-get install -y docker-compose-plugin

# ── 3. System limits for high concurrency ─────────────────────────
echo "[3/7] Configuring system limits..."

# File descriptor limits (needed for 10k connections)
cat >> /etc/security/limits.conf << 'EOF'
*    soft nofile 65536
*    hard nofile 65536
root soft nofile 65536
root hard nofile 65536
EOF

# TCP tuning for high throughput
cat >> /etc/sysctl.conf << 'EOF'
# URL Shortener performance tuning
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 5000
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_max_tw_buckets = 1440000
vm.swappiness = 10
EOF
sysctl -p

# ── 4. Install k6 (load testing) ──────────────────────────────────
echo "[4/7] Installing k6..."
gpg -k
gpg --no-default-keyring \
    --keyring /usr/share/keyrings/k6-archive-keyring.gpg \
    --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 2>/dev/null || true

echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" \
    | tee /etc/apt/sources.list.d/k6.list
apt-get update -q
apt-get install -y k6 2>/dev/null || echo "k6 install optional — skipping"

# ── 5. Clone repository ───────────────────────────────────────────
echo "[5/7] Setting up application..."
APP_DIR="/opt/url-shortener"
mkdir -p "$APP_DIR"

# If running from repo, copy files; else clone
if [ -d "/tmp/url-shortener" ]; then
    cp -r /tmp/url-shortener/. "$APP_DIR/"
else
    echo "Place your code in $APP_DIR or update this script with your GitHub repo URL."
    echo "Example: git clone https://github.com/YOUR_USER/url-shortener.git $APP_DIR"
fi

chown -R ubuntu:ubuntu "$APP_DIR"

# ── 6. Environment config ─────────────────────────────────────────
echo "[6/7] Writing .env file..."
# Get EC2 public IP for APP_BASE_URL
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "localhost")

cat > "$APP_DIR/.env" << EOF
# Auto-generated by ec2-setup.sh on $(date)
APP_BASE_URL=http://${PUBLIC_IP}:8080
DATABASE_URL=jdbc:postgresql://postgres:5432/urlshortener
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=$(openssl rand -hex 16)
REDIS_HOST=redis
REDIS_PORT=6379
SNOWFLAKE_MACHINE_ID=1
CORS_ALLOWED_ORIGINS=http://${PUBLIC_IP}:3000,http://${PUBLIC_IP}
EOF

echo "Public IP: $PUBLIC_IP"
echo ".env written to $APP_DIR/.env"

# ── 7. Start services ─────────────────────────────────────────────
echo "[7/7] Starting Docker services..."
cd "$APP_DIR"
docker compose pull 2>/dev/null || true
docker compose up -d --build

# Wait for health
echo "Waiting for services to be healthy..."
sleep 30

docker compose ps

echo ""
echo "========================================"
echo " Setup complete!"
echo " Frontend:  http://${PUBLIC_IP}:3000"
echo " API:       http://${PUBLIC_IP}:8080"
echo " Grafana:   http://${PUBLIC_IP}:3001"
echo " Prometheus:http://${PUBLIC_IP}:9090"
echo ""
echo " Load test: k6 run k6/load-test.js"
echo "========================================"
